[package]
name = "download-manager"
description = "A small async download manager for Bottles Next written in Rust, built with reqwest and tokio."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/bottlesdevs/next-download-manager"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]
readme = "README.md"

[lib]
path = "src/download_manager.rs"

[dependencies]
reqwest.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
futures-core.workspace = true
futures-util.workspace = true
thiserror.workspace = true
anyhow.workspace = true
derive_builder.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
